; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/Users/jamiely/code/tetris-attack-clojure/src/clj/attack/cursor.clj

(ns attack.cursor
  (:require [attack.point :as pt]))

(defn default []
  {:origin (pt/point 2 15)})

