; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/Users/jamiely/code/tetris-attack-clojure/src/clj/attack/display_math.clj

(ns attack.display-math)

(defn pt-to-display-pt [{total-rows :total-rows
                         bheight :block-height
                         bwidth :block-width
                         dheight :display-height} [x y]]
  (let [diff (- total-rows y)
        adj-y (* (+ diff 1) bheight)
        y (- dheight adj-y)]
    [(* x bwidth) y]))
