; DO NOT EDIT THIS FILE! IT WAS AUTOMATICALLY GENERATED BY
; lein-cljsbuild FROM THE FOLLOWING SOURCE FILE:
; file:/Users/jamiely/code/tetris-attack-clojure/src/clj/attack/game_interface.clj

(ns attack.game-interface
  (:require [attack.game :as game]
            [attack.cursor :as cursor]))

(defn default []
  {:game (game/default)
   :cursor (cursor/default)})

(defn step [{game :game :as gi}]
  (assoc gi :game (game/step game)))
